export const APARTMENTS = [
  {
    slug: "pearl-suite",
    name: "The Pearl Suite",
    description:
      "A spacious one-bedroom apartment with a modern kitchen, living area, and private balcony overlooking the neighborhood.",
    price: 100000,
    beds: 1,
    guests: 2,
    gradient: "from-[#1a1a1a] to-[#2a2520]",
    cover: null,
    images: [],
    amenities: [
      "Wi-Fi",
      "Air Conditioning",
      "Kitchen",
      "Balcony",
      "Smart TV",
      "Washer",
    ],
  },
  {
    slug: "coral-residence",
    name: "The Coral Residence",
    description:
      "Our two-bedroom apartment perfect for families or groups, featuring a full kitchen, dining area, and cozy lounge.",
    price: 150000,
    beds: 2,
    guests: 4,
    gradient: "from-[#2a2520] to-[#1a1a1a]",
    cover: "/images/apartments/vv-14.jpg",
    images: [
      "/images/apartments/vv-03.jpg",
      "/images/apartments/vv-11.jpg",
      "/images/apartments/vv-12.jpg",
      "/images/apartments/vv-13.jpg",
      "/images/apartments/vv-27.jpg",
      "/images/apartments/vv-28.jpg",
      "/images/apartments/vv-37.jpg",
    ],
    amenities: [
      "Wi-Fi",
      "Air Conditioning",
      "Full Kitchen",
      "Dining Area",
      "Smart TV",
      "Washer",
      "Workspace",
    ],
  },
  {
    slug: "gold-penthouse",
    name: "The Gold Penthouse",
    description:
      "The premium four-bedroom penthouse with panoramic views, luxury finishes, and a spacious open-plan living area.",
    price: 300000,
    beds: 4,
    guests: 12,
    gradient: "from-[#1a1a1a] to-[#2a2018]",
    cover: "/images/apartments/vv-09.jpg",
    images: [
      "/images/apartments/vv-01.jpg",
      "/images/apartments/vv-02.jpg",
      "/images/apartments/vv-04.jpg",
      "/images/apartments/vv-05.jpg",
      "/images/apartments/vv-06.jpg",
      "/images/apartments/vv-07.jpg",
      "/images/apartments/vv-08.jpg",
      "/images/apartments/vv-09.jpg",
      "/images/apartments/vv-10.jpg",
      "/images/apartments/vv-14.jpg",
      "/images/apartments/vv-15.jpg",
      "/images/apartments/vv-16.jpg",
      "/images/apartments/vv-17.jpg",
      "/images/apartments/vv-18.jpg",
      "/images/apartments/vv-19.jpg",
      "/images/apartments/vv-20.jpg",
      "/images/apartments/vv-29.jpg",
      "/images/apartments/vv-33.jpg",
      "/images/apartments/vv-34.jpg",
    ],
    amenities: [
      "Wi-Fi",
      "Air Conditioning",
      "Gourmet Kitchen",
      "Panoramic Views",
      "Smart TV",
      "Washer",
      "Workspace",
      "Premium Linens",
      "Espresso Machine",
    ],
  },
] as const;

export type ApartmentSlug = (typeof APARTMENTS)[number]["slug"];
